{
 "title": "Smart-Agricolture",
 "time": { "from": "2023-12-19T02:32:31.000Z", "to": "2023-12-19T02:33:30.000Z" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT * FROM smart_agricolture.temperature LIMIT 50 "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT * FROM smart_agricolture.humidity LIMIT 50 "
    }
   ]
  },
  {
   "title": "AVGSoilHumidity1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT AVG(value) FROM smart_agricolture.soilHumidity WHERE nodeId = 19836 ORDER BY timestamp DESC LIMIT 6 "
    }
   ]
  },
  {
   "title": "AVGSoilHumidity2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT AVG(value) FROM smart_agricolture.soilHumidity WHERE nodeId = 23778 ORDER BY timestamp DESC LIMIT 6 "
    }
   ]
  },
  {
   "title": "SoilHumidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT * FROM smart_agricolture.soilHumidity LIMIT 50 "
    }
   ]
  },
  {
   "title": "AVGSoilHumidity1-cooja",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT AVG(value) FROM smart_agricolture.soilHumidity WHERE nodeId = 3 ORDER BY timestamp DESC LIMIT 6 "
    }
   ]
  },
  {
   "title": "AVGSoilHumidity2-cooja",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT AVG(value) FROM smart_agricolture.soilHumidity WHERE nodeId = 8 ORDER BY timestamp DESC LIMIT 6 "
    }
   ]
  }
 ]
}