{
 "title": "Smart-Agricolture",
 "time": { "from": "2023-12-18T16:22:55.999Z", "to": "2023-12-18T16:36:07.400Z" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT * FROM smart_agricolture.temperature LIMIT 50 "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT * FROM smart_agricolture.humidity LIMIT 50 "
    }
   ]
  },
  {
   "title": "SoilHumidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT * FROM smart_agricolture.soilHumidity LIMIT 50 "
    }
   ]
  },
  {
   "title": "AVGSoilHumidity3",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT AVG(value) FROM smart_agricolture.soilHumidity WHERE nodeId = 3 LIMIT 50 "
    }
   ]
  },
  {
   "title": "AVGSoilHumidity8",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT AVG(value) FROM smart_agricolture.soilHumidity WHERE nodeId = 8 LIMIT 50 "
    }
   ]
  }
 ]
}