{
 "title": "Smart-Agricolture",
 "time": { "from": "now +1h - 3m", "to": "now +1h" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT * FROM smart_agricolture.temperature LIMIT 50 "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT * FROM smart_agricolture.humidity LIMIT 50 "
    }
   ]
  },
  {
   "title": "SoilHumidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT * FROM smart_agricolture.soilHumidity LIMIT 50 "
    }
   ]
  },
  {
   "title": "AVGSoilHumidity1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT AVG(value) FROM smart_agricolture.soilHumidity WHERE (nodeId = 19836 AND timestamp >= (now() - interval 20 second)) "
    }
   ]
  },
  {
   "title": "AVGSoilHumidity2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT AVG(value) FROM smart_agricolture.soilHumidity WHERE (nodeId = 23778 AND timestamp >= (now() - interval 20 second))"
    }
   ]
  },
  {
   "title": "AVGSoilHumidity1-cooja",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT AVG(value) FROM smart_agricolture.soilHumidity WHERE (nodeId = 3 AND timestamp >= (now() - interval 20 second))"
    }
   ]
  },
  {
   "title": "AVGSoilHumidity2-cooja",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_agricolture",
     "rawSql": "SELECT AVG(value) FROM smart_agricolture.soilHumidity WHERE (nodeId = 8 AND timestamp >= (now() - interval 20 second))"
    }
   ]
  }
 ]
}